/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Finder-Control.h
 #	source generated by 4D Plugin Wizard
 #	Project : Finder Control
 #	author : miyako
 #	2020/09/03
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_FINDER_CONTROL_H
#define PLUGIN_FINDER_CONTROL_H

#import <ScriptingBridge/ScriptingBridge.h>
#include "4DPluginAPI.h"
#include "C_TEXT.h"
#include "C_LONGINT.h"
#include "ARRAY_TEXT.h"
#include "Finder.h"

#pragma mark -

void Finder_set_comment(PA_PluginParameters params);
void Finder_get_comment(PA_PluginParameters params);
void Finder_set_locked(PA_PluginParameters params);
void Finder_get_locked(PA_PluginParameters params);
void Finder_set_extension_hidden(PA_PluginParameters params);
void Finder_get_extension_hidden(PA_PluginParameters params);
void Finder_SORT_ARRAY(PA_PluginParameters params);
void Finder_get_display_name(PA_PluginParameters params);
void Finder_get_description(PA_PluginParameters params);
void Finder_get_kind(PA_PluginParameters params);
void Finder_reveal(PA_PluginParameters params);
void Finder_trash(PA_PluginParameters params);

#endif /* PLUGIN_FINDER_CONTROL_H */
